/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearAllInquiries' : IDL.Func([], [], []),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAllInquiriesSortedByName' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getInquiryById' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
  'getInquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'clearAllInquiries' : IDL.Func([], [], []),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAllInquiriesSortedByName' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getInquiryById' : IDL.Func([IDL.Nat], [Inquiry], ['query']),
    'getInquiryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };